kind: Deployment
apiVersion: apps/v1
metadata:
  name: hf-text-generation-inference-server-model1
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: MODEL_ID
              value: google/flan-t5-xl
            - name: MAX_INPUT_LENGTH
              value: '1024'
            - name: MAX_TOTAL_TOKENS
              value: '2048'
            - name: QUANTIZE
              value: bitsandbytes
            - name: HUGGINGFACE_HUB_CACHE
              value: /models-cache
            - name: PORT
              value: '3000'
            - name: HOST
              value: 0.0.0.0
            - name: HUGGING_FACE_HUB_TOKEN
              $patch: delete
