kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: llm-ui
  labels:
    app: gradio-hftgi-rag-redis
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  to:
    kind: Service
    name: gradio-hftgi-rag-redis-mistral
    weight: 50
  alternateBackends:
    - kind: Service
      name: gradio-hftgi-rag-redis-flan
      weight: 50
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
