kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tgis-server-mistral
  labels:
    app: hf-text-generation-inference-server-mistral
spec:
  to:
    kind: Service
    name: hf-text-generation-inference-server-mistral
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
