kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tgis-server
  labels:
    app: hf-text-generation-inference-server
spec:
  to:
    kind: Service
    name: hf-text-generation-inference-server-flan
    weight: 50
  alternateBackends:
    - kind: Service
      name: hf-text-generation-inference-server-mistral
      weight: 50
  port:
    targetPort: http
  wildcardPolicy: None