apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ai-llm-prometheus
spec:
  evaluationInterval: 10s
  resources:
    requests:
      memory: 400Mi
  scrapeInterval: 30s
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      app: frontend
