kind: Service
apiVersion: v1
metadata:
  name: hf-text-generation-inference-server
  labels:
    app: hf-text-generation-inference-server
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: hf-text-generation-inference-server