apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-llm-monitoring-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
